global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'inventory-simulator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Assuming Spring Boot application is on host machine port 8080
      - targets: ['host.docker.internal:8080']

