global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'inventory-simulator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 假設 Spring Boot 應用在宿主機的 8080 port
      - targets: ['host.docker.internal:8080']

